# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxAwx3Iq02yddsgI11Ev_nmUz_1_c8fx
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV3URJSUVe3vtw0O7ZOH55jfJtdWDJ2v
"""

# Install streamlit if it's not already installed


import streamlit as st
import pickle
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import re
import string

# ✅ FIRST Streamlit command
st.set_page_config(page_title="Spam Classifier", page_icon="📧", layout="centered")

nltk.download('stopwords')

# Load model and vectorizer
model = pickle.load(open('model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

# Preprocessing function
def preprocess(text):
    text = text.lower()
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    tokens = text.split()
    tokens = [word for word in tokens if word not in stopwords.words("english")]
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    return " ".join(tokens)

# Streamlit UI
st.title("Spam Classifier")
user_input = st.text_area("Enter a message:")

if st.button("Predict"):
    cleaned = preprocess(user_input)
    vect_text = vectorizer.transform([cleaned])
    prediction = model.predict(vect_text)[0]
    st.write("### Prediction:", "🚫 Spam" if prediction == "spam" else "✅ Not Spam")

