# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxAwx3Iq02yddsgI11Ev_nmUz_1_c8fx
"""

# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV3URJSUVe3vtw0O7ZOH55jfJtdWDJ2v
"""

# Install streamlit if it's not already installed


# streamlit_app.py
import streamlit as st
import pickle

# Load model and vectorizer
# Ensure 'model.pkl' and 'vectorizer.pkl' exist in the same directory
try:
    model = pickle.load(open('model.pkl', 'rb'))
    vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))
except FileNotFoundError:
    st.error("Error: model.pkl or vectorizer.pkl not found. Please ensure these files are in the same directory.")
    st.stop() # Stop the streamlit app if files are missing


st.set_page_config(page_title="Spam vs Ham Classifier")
st.title("📨 Spam vs Ham Email Classifier")
st.write("Enter an email or message to classify it as spam or ham.")

# User input
user_input = st.text_area("Your message here:")

if st.button("Classify"):
    if user_input.strip() == "":
        st.warning("Please enter a message.")
    else:
        transformed = vectorizer.transform([user_input])
        prediction = model.predict(transformed)[0]
        st.success(f"🧠 Prediction: **{'Spam' if prediction == 'spam' else 'Ham'}**")
